name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main   # change this if your main branch is named differently

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # 🔹 Generate dynamic image tag
      - name: Generate image tag
        run: |
          echo "IMAGE_TAG=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .                     # directory to look for Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker:${{ env.IMAGE_TAG }}

        # Optional: Output tag for debugging or CF deploy
      - name: Echo image tag
        run: |
          echo "Pushed tag: ${{ env.IMAGE_TAG }}"
